# Copyright 2024 OpenSynergy Indonesia
# Copyright 2024 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

from odoo import api, fields, models


class SchoolAdmissionFormCreateAdmission(models.TransientModel):
    """
    Wizard that creates (or reopens) the school_admission generated by
    a school_admission_form, letting the operator override the
    pricelist, receivable journal/account, and customer invoice
    settings before the admission is created.
    """

    _name = "school_admission_form.wizard_create_admission"
    _description = "Create School Admission from Admission Form"

    admission_form_id = fields.Many2one(
        string="Admission Form",
        comodel_name="school_admission_form",
        required=True,
        readonly=True,
    )
    currency_id = fields.Many2one(
        string="Currency",
        comodel_name="res.currency",
        required=True,
        default=lambda self: self.env.company.currency_id,
    )
    allowed_pricelist_ids = fields.Many2many(
        string="Allowed Pricelists",
        comodel_name="product.pricelist",
        compute="_compute_allowed_pricelist_ids",
        store=False,
    )
    pricelist_id = fields.Many2one(
        string="Pricelist",
        comodel_name="product.pricelist",
        required=False,
    )
    payment_template_id = fields.Many2one(
        string="Payment Template",
        comodel_name="school_admission_payment_template",
        required=False,
    )
    receivable_journal_id = fields.Many2one(
        string="Receivable Journal",
        comodel_name="account.journal",
        required=False,
    )
    receivable_account_id = fields.Many2one(
        string="Receivable Account",
        comodel_name="account.account",
        required=False,
    )
    customer_invoice_type_id = fields.Many2one(
        string="Customer Invoice Type",
        comodel_name="customer_invoice_type",
        required=False,
        help=(
            "Customer invoice type applied to the admission created by "
            "this wizard. Auto-populated from the selected payment "
            "template, but can be overridden."
        ),
    )
    auto_confirm_customer_invoice = fields.Boolean(
        string="Auto Confirm Customer Invoice",
        default=False,
        help=(
            "If enabled, the customer invoice created from the "
            "admission's payment terms is immediately confirmed instead "
            "of being left in draft. Auto-populated from the selected "
            "payment template, but can be overridden."
        ),
    )

    @api.model
    def default_get(self, fields_list):
        """Prefill the admission form from the active record.

        :param fields_list: names of the fields to default
        :return: dict of default values
        """
        res = super().default_get(fields_list)
        active_id = self.env.context.get("active_id")
        if active_id:
            res["admission_form_id"] = active_id
        return res

    @api.depends("currency_id")
    def _compute_allowed_pricelist_ids(self):
        """List the pricelists usable with the selected currency.

        Searches ``product.pricelist`` for records whose currency equals
        ``currency_id``; the result feeds the domain of ``pricelist_id``.
        Empty when no currency is set yet.
        """
        Pricelist = self.env["product.pricelist"]  # pylint: disable=invalid-name
        for record in self:
            result = []
            if record.currency_id:
                criteria = [("currency_id", "=", record.currency_id.id)]
                result = Pricelist.search(criteria).ids
            record.allowed_pricelist_ids = result

    @api.onchange("currency_id")
    def onchange_pricelist_id(self):
        """Clear the pricelist when the currency changes."""
        self.pricelist_id = False

    @api.onchange(
        "payment_template_id",
    )
    def onchange_customer_invoice_type_id(self):
        self.customer_invoice_type_id = False
        if self.payment_template_id:
            self.customer_invoice_type_id = (
                self.payment_template_id.customer_invoice_type_id
            )

    @api.onchange(
        "payment_template_id",
    )
    def onchange_auto_confirm_customer_invoice(self):
        self.auto_confirm_customer_invoice = False
        if self.payment_template_id:
            self.auto_confirm_customer_invoice = (
                self.payment_template_id.auto_confirm_customer_invoice
            )

    def action_create_admission(self):
        """Create the admission from the admission form, or reopen it.

        Idempotent: if a ``school_admission`` already links to
        ``admission_form_id``, that existing record is reopened and no
        new one is created. ``customer_invoice_type_id`` and
        ``auto_confirm_customer_invoice`` are copied from the wizard
        (auto-populated by onchange from ``payment_template_id``, but
        overridable) into the created admission, same as
        ``receivable_journal_id``/``receivable_account_id``.

        :return: an ``ir.actions.act_window`` dict opening the
            (created or existing) ``school_admission`` form
        """
        self.ensure_one()
        form = self.admission_form_id
        SchoolAdmission = self.env["school_admission"]  # pylint: disable=invalid-name
        existing = SchoolAdmission.search(
            [("admission_form_id", "=", form.id)], limit=1
        )
        if existing:
            admission = existing
        else:
            admission = SchoolAdmission.create(
                {
                    "date": form.date,
                    "academic_year_id": form.academic_year_id.id,
                    "academic_term_id": form.academic_term_id.id,
                    "school_id": form.school_id.id,
                    "grade_id": form.grade_id.id,
                    "student_id": form.student_id.id,
                    "admission_form_id": form.id,
                    "admission_test_id": form.admission_test_id.id
                    if form.admission_test_id
                    else False,
                    "currency_id": self.currency_id.id,
                    "pricelist_id": self.pricelist_id.id
                    if self.pricelist_id
                    else False,
                    "payment_template_id": self.payment_template_id.id
                    if self.payment_template_id
                    else False,
                    "receivable_journal_id": self.receivable_journal_id.id
                    if self.receivable_journal_id
                    else False,
                    "receivable_account_id": self.receivable_account_id.id
                    if self.receivable_account_id
                    else False,
                    "customer_invoice_type_id": self.customer_invoice_type_id.id
                    if self.customer_invoice_type_id
                    else False,
                    "auto_confirm_customer_invoice": self.auto_confirm_customer_invoice,
                }
            )
        return {
            "type": "ir.actions.act_window",
            "name": "School Admission",
            "res_model": "school_admission",
            "res_id": admission.id,
            "view_mode": "form",
            "target": "current",
        }
