# Copyright 2026 OpenSynergy Indonesia
# Copyright 2026 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

from odoo import _, fields, models
from odoo.exceptions import UserError


class SchoolAdmissionWizardCreateEnrollment(models.TransientModel):
    """
    Wizard that creates a draft school_enrollment for the school_student
    generated by a school_admission, using the admission's academic year/
    term, school and grade, plus an operator-selected grade class and
    payment template. Idempotent: if the admission is already linked to
    an enrollment, no new enrollment is created.
    """

    _name = "school_admission.wizard_create_enrollment"
    _description = "Create School Enrollment from School Admission"

    admission_id = fields.Many2one(
        string="Admission",
        comodel_name="school_admission",
        required=True,
        readonly=True,
        help="The admission this enrollment will be generated from.",
    )
    grade_class_id = fields.Many2one(
        string="Grade Class",
        comodel_name="school_grade_class",
        required=True,
        help="The homeroom class the student will be placed in.",
    )
    payment_template_id = fields.Many2one(
        string="Payment Template",
        comodel_name="school_enrollment_payment_template",
        required=False,
        help=(
            "The enrollment payment template used to auto-populate "
            "billing terms. Left empty, no payment terms are generated."
        ),
    )
    receivable_journal_id = fields.Many2one(
        string="Receivable Journal",
        comodel_name="account.journal",
        required=False,
        help="The journal used to post receivable entries for the enrollment.",
    )
    receivable_account_id = fields.Many2one(
        string="Receivable Account",
        comodel_name="account.account",
        required=False,
        help="The account used to record receivables for the enrollment.",
    )
    pricelist_id = fields.Many2one(
        string="Pricelist",
        comodel_name="product.pricelist",
        required=False,
        help="The pricelist applied for price calculations in the enrollment.",
    )
    currency_id = fields.Many2one(
        string="Currency",
        comodel_name="res.currency",
        required=True,
        default=lambda self: self.env.company.currency_id,
        help="The currency used for the enrollment payment billing.",
    )

    def action_create_enrollment(self):
        """Create the draft enrollment, or open the existing linked one.

        Delegates to ``_create_enrollment`` under ``sudo()``, since
        creating a ``school_enrollment`` and linking it back to the
        admission must not depend on the current user also holding
        ``school_enrollment`` module access or admission write rights
        (mirrors ``action_create_due_invoice`` on ``school_admission``).
        Returns an act_window opening the resulting (or pre-existing)
        ``school_enrollment`` form.

        :return: an ``ir.actions.act_window`` dict
        """
        self.ensure_one()
        enrollment = self.sudo()._create_enrollment()
        return {
            "type": "ir.actions.act_window",
            "name": "School Enrollment",
            "res_model": "school_enrollment",
            "res_id": enrollment.id,
            "view_mode": "form",
            "target": "current",
        }

    def _create_enrollment(self):
        """Create the draft school_enrollment for the admission's student.

        Guard: if ``admission_id.enrollment_id`` is already set, that
        existing enrollment is returned as-is and no new record is
        created (idempotent on repeated calls). ``grade_id`` is always
        copied from the admission (transfer-in is out of scope for this
        wizard).

        :return: the created (or existing) ``school_enrollment`` record
        """
        self.ensure_one()
        admission = self.admission_id
        if admission.enrollment_id:
            return admission.enrollment_id
        self._check_school_student()
        enrollment = self.env["school_enrollment"].create(
            {
                "date": admission.date,
                "academic_year_id": admission.academic_year_id.id,
                "academic_term_id": admission.academic_term_id.id,
                "school_id": admission.school_id.id,
                "grade_id": admission.grade_id.id,
                "grade_class_id": self.grade_class_id.id,
                "student_id": admission.school_student_id.id,
                "currency_id": self.currency_id.id,
                "pricelist_id": self.pricelist_id.id if self.pricelist_id else False,
                "receivable_journal_id": self.receivable_journal_id.id
                if self.receivable_journal_id
                else False,
                "receivable_account_id": self.receivable_account_id.id
                if self.receivable_account_id
                else False,
                "payment_template_id": self.payment_template_id.id
                if self.payment_template_id
                else False,
            }
        )
        admission.write({"enrollment_id": enrollment.id})
        return enrollment

    def _check_school_student(self):
        """Ensure the admission already has a linked school_student.

        :raises UserError: if ``admission_id.school_student_id`` is not
            set, since ``school_enrollment.student_id`` requires it.
        """
        self.ensure_one()
        if not self.admission_id.school_student_id:
            error_message = (
                _(
                    """
Context: Create enrollment from admission
Database ID: %s
Problem: Admission has no linked school student yet
Solution: Open the admission first so its school student is created
"""
                )
                % (self.admission_id.id,)
            )
            raise UserError(error_message)
