# Copyright 2024 OpenSynergy Indonesia
# Copyright 2024 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

from . import (  # noqa: F401
    common,
    test_hr_employee,
    test_school_grade_type,
    test_school_grade,
    test_school_branch,
    test_school,
    test_school_integrity,
    test_school_grade_class,
    test_school_academic_year,
    test_school_academic_term,
    test_school_teacher,
    test_school_student,
    test_school_student_personal_data,
    test_school_student_family,
    test_school_student_states,
    test_school_enrollment_payment_template,
    test_school_enrollment_payment_product_configurator,
    test_school_enrollment,
    test_school_enrollment_access,
    test_school_enrollment_results,
    test_school_enrollment_payment_term_management,
    test_school_enrollment_payment_term_duplicate,
    test_school_enrollment_copy_payment_term,
    test_school_enrollment_create_due_invoice,
    test_school_enrollment_customer_invoice,
    test_school_enrollment_product_summary,
    test_school_enrollment_fee_analysis,
    test_school_enrollment_payment_date_pattern,
    test_school_enrollment_addendum,
    test_school_enrollment_restart_unlock,
    test_school_enrollment_integrity,
    test_school_homeroom,
    test_school_homeroom_integrity,
    test_school_homeroom_generate,
    test_school_student_mutation,
)
