# Copyright 2022 OpenSynergy Indonesia
# Copyright 2022 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
{
    "name": "School",
    "version": "14.0.4.5.0",
    "website": "https://simetri-sinergi.id",
    # pylint: disable=line-too-long
    "author": "PT. Simetri Sinergi Indonesia, OpenSynergy Indonesia, Odoo Community Association (OCA)",  # noqa: B950
    # pylint: enable=line-too-long
    "license": "AGPL-3",
    "installable": True,
    "application": True,
    "depends": [
        "ssi_master_data_mixin",
        "ssi_transaction_confirm_mixin",
        "ssi_transaction_open_mixin",
        "ssi_transaction_done_mixin",
        "ssi_transaction_cancel_mixin",
        "ssi_localdict_mixin",
        "ssi_product_line_account_mixin",
        "base_address_city",
        "ssi_financial_accounting",
    ],
    "data": [
        "security/ir_module_category_data.xml",
        "security/ir_module_category/school_enrollment.xml",
        "security/res_group_data.xml",
        "security/res_group/school_enrollment.xml",
        "security/ir_model_access/school_grade_type.xml",
        "security/ir_model_access/school_grade.xml",
        "security/ir_model_access/school.xml",
        "security/ir_model_access/school_grade_class.xml",
        "security/ir_model_access/school_student.xml",
        "security/ir_model_access/school_teacher.xml",
        "security/ir_model_access/school_academic_year.xml",
        "security/ir_model_access/school_academic_term.xml",
        "security/ir_model_access/school_enrollment.xml",
        "security/ir_model_access/school_enrollment_payment_term.xml",
        "security/ir_model_access/school_enrollment_payment_term_detail.xml",
        "security/ir_model_access/school_enrollment_payment_template.xml",
        "security/ir_rule/school_enrollment.xml",
        "ir_sequence/school_enrollment.xml",
        "sequence_template/school_enrollment.xml",
        "policy_template/school_enrollment.xml",
        "approval_template/school_enrollment.xml",
        "menu.xml",
        "views/school_grade_type.xml",
        "views/school_grade.xml",
        "views/school.xml",
        "views/school_grade_class.xml",
        "views/school_student.xml",
        "views/school_teacher.xml",
        "views/school_academic_year.xml",
        "views/school_academic_term.xml",
        "views/school_enrollment.xml",
        "views/school_enrollment_payment_term_views.xml",
        "views/school_enrollment_payment_template_views.xml",
    ],
    "demo": [
        "demo/res_partner.xml",
        "demo/school_grade_type.xml",
        "demo/school_grade.xml",
        "demo/school.xml",
        "demo/school_grade_class.xml",
        "demo/school_academic_year.xml",
        "demo/school_academic_term.xml",
        "demo/school_student.xml",
        "demo/school_teacher.xml",
    ],
}
