# Copyright 2022 OpenSynergy Indonesia
# Copyright 2022 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
{
    "name": "School Admission",
    "version": "14.0.2.6.0",
    "website": "https://simetri-sinergi.id",
    "author": (
        "PT. Simetri Sinergi Indonesia, "
        "OpenSynergy Indonesia, "
        "Odoo Community Association (OCA)"
    ),
    "license": "AGPL-3",
    "installable": True,
    "depends": [
        "ssi_school",
        "ssi_master_data_mixin",
        "ssi_transaction_confirm_mixin",
        "ssi_transaction_open_mixin",
        "ssi_transaction_done_mixin",
        "ssi_transaction_cancel_mixin",
        "ssi_accounting_entry_mixin",
        "ssi_company_currency_mixin",
        "ssi_transaction_total_mixin",
        "ssi_product_line_account_mixin",
        "base_automation",
    ],
    "data": [
        "ir_module_category/school_admission_form.xml",
        "ir_module_category/school_admission_test.xml",
        "res_group/res_group.xml",
        "res_group/school_admission_form.xml",
        "res_group/school_admission_test.xml",
        "ir_model_access/school_admission_fee_template.xml",
        "ir_model_access/school_admission_form.xml",
        "ir_model_access/school_admission_form_wizard_create_admission.xml",
        "ir_model_access/school_admission_test.xml",
        "ir_model_access/school_admission_test_wizard_create_admission.xml",
        "ir_rule/school_admission_form.xml",
        "ir_rule/school_admission_test.xml",
        "ir_sequence/school_admission_form.xml",
        "ir_sequence/school_admission_test.xml",
        "sequence_template/school_admission_form.xml",
        "sequence_template/school_admission_test.xml",
        "policy_template/school_admission_form.xml",
        "policy_template/school_admission_test.xml",
        "approval_template/school_admission_form.xml",
        "approval_template/school_admission_test.xml",
        "data/base_automation_data.xml",
        "wizards/school_admission_form_create_admission.xml",
        "wizards/school_admission_test_create_admission.xml",
        "menu.xml",
        "views/school_admission_fee_template.xml",
        "views/school_admission_form.xml",
        "views/school_admission_test.xml",
        "ir_module_category/school_admission.xml",
        "res_group/school_admission.xml",
        "ir_model_access/school_admission.xml",
        "ir_model_access/school_admission_product_summary.xml",
        "ir_model_access/school_admission_payment_template.xml",
        "ir_model_access/school_admission_payment_term.xml",
        "ir_rule/school_admission.xml",
        "ir_sequence/school_admission.xml",
        "sequence_template/school_admission.xml",
        "policy_template/school_admission.xml",
        "approval_template/school_admission.xml",
        "views/school_admission_payment_template.xml",
        "views/school_admission_payment_term.xml",
        "views/school_admission.xml",
    ],
    "demo": [
        "demo/account_account_demo.xml",
        "demo/account_journal_demo.xml",
        "demo/product_product_demo.xml",
        "demo/school_admission_fee_template_demo.xml",
        "demo/school_admission_payment_template_demo.xml",
    ],
}
